language: java
sudo: false
jdk:
- openjdk8
before_install:
- mkdir -p /home/travis/build/bioatlas/oztrack/target/classes/; wsimport -extension
  http://ws-argos.clsamerica.com/argosDws/services/DixService?wsdl -d /home/travis/build/bioatlas/oztrack/target/classes/;
script: mvn package
deploy:
  provider: releases
  api_key:
    secure: mThdVRbPM27XXIQJxLWdE3jCekS+/vbyRsAnsXPgJ+xA+KmY5jUvfe135oTZqVjxyHSKvmcLEq8Ls/EuuvDEoAH1dThbEhl0IZFNP9bCVO4B+KMCDJ6j8FDSWEK7s92uCahb6IrRhSaSllSE2LDd2UeLBMysOCABAA61UQizxNw0QXrLvDt29TN6eNyAzLXVZs/LW1ZYV6daMx9tY29ts4s9CTy5rAi5R3ff6oJN1imgs7r2KgbyNgaAtd2A0KRY/vu1eyVO99siyAX2tUJBQAQLhCmj2XUyiqQ0ljVb9xNkhzhiSkXOC89suG0R0KEivs+rwsnxnPXljHdO9FnK4d2rLJQZ9vL3O4LqY4KkMUkbTY649HpDdmY9H0xPHaT4xQdO8ceF/8Hw5/65T3eCW/MdBfkbvB6AcpNnvj1RRCdb0OjIViFK8o0yvufKQcK+dL8nmw3zWmdIH5TxvjpN0wx4fgueMn5GDYeWVlAxK0kU7g9gwHvQE9nLqXHHIWgWVxvO1J2i27C00Zp3eH4PxjLoyYcn07/P388/N3+Wp+llH0SHkamvRq2j0OulrXiBVOGCp7VChhwZgbcR2CSgLW8P55B4tj7oOjinxeeCMb6fFDF/TDUUbfxKT3qQv/+T4AB3yjLQjE2/CVm+fYLDfJ2GkD/uwifrRigLDWZS97w=
  file_glob: true
  file: target/oztrack*.war
  skip_cleanup: true
  overwrite: true
  on:
    repo: bioatlas/oztrack
    all-branches: true
    tags: true